import React, { useState, useEffect } from "react";
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  Alert,
  ActivityIndicator,
  Image,                    // ← Added this import
} from "react-native";

import Icon from "react-native-vector-icons/Ionicons";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import * as FileSystem from "expo-file-system/legacy";
import * as ImagePicker from "expo-image-picker";
import AsyncStorage from "@react-native-async-storage/async-storage";
import { useNavigation } from "@react-navigation/native";

import { useAuth } from "../context/AuthContext";
import { getMonthlyReport } from "../api/reportApi";

export default function ProfileScreen() {
  const { user, logout } = useAuth();
  const navigation = useNavigation();

  const [profileImage, setProfileImage] = useState(null);
  const [generatingReport, setGeneratingReport] = useState(false);

  useEffect(() => {
    loadProfileImage();
  }, []);

  const loadProfileImage = async () => {
    try {
      const savedImage = await AsyncStorage.getItem("profileImage");
      if (savedImage) setProfileImage(savedImage);
    } catch (error) {
      console.error(error);
    }
  };

  const pickImage = async () => {
    try {
      const result = await ImagePicker.launchImageLibraryAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.Images,
        allowsEditing: true,
        aspect: [1, 1],
        quality: 1,
      });

      if (!result.canceled) {
        const imageUri = result.assets[0].uri;
        setProfileImage(imageUri);
        await AsyncStorage.setItem("profileImage", imageUri);
      }
    } catch (error) {
      console.error(error);
      Alert.alert("Error", "Failed to pick image");
    }
  };

  const generateReport = async () => {
    setGeneratingReport(true);
    try {
      const report = await getMonthlyReport();

      const html = `
        <html>
        <head><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
        <body style="font-family: Arial, sans-serif; padding: 40px; background: #0F172A; color: #fff;">
          <h1 style="color: #60A5FA;">Smart Finance • Monthly Report</h1>
          <p style="color: #94A3B8;">Generated on ${new Date().toLocaleDateString()}</p>
          <hr style="border-color: #334155;">
          
          <h2>Budget Summary</h2>
          <p><strong>Budget:</strong> ₹${report.budget || 0}</p>
          <p><strong>Total Spent:</strong> ₹${report.totalSpent || 0}</p>
          <p><strong>Remaining:</strong> ₹${report.remaining || 0}</p>
          <p><strong>Usage:</strong> ${report.usagePercentage || 0}%</p>
          
          <hr style="border-color: #334155;">
          
          <h2>Top Category</h2>
          <p><strong>${report.topCategory?.category || "N/A"}</strong> — ₹${report.topCategory?.amount || 0}</p>
          
          <hr style="border-color: #334155;">
          
          <h2>🤖 AI Insights</h2>
          ${report.aiInsights?.map(insight => `<p>• ${insight}</p>`).join("") || "<p>No insights available yet.</p>"}
          
          <p style="margin-top: 50px; color: #64748B; text-align: center;">
            Generated by Smart Finance Tracker
          </p>
        </body>
        </html>
      `;

      const { uri } = await Print.printToFileAsync({ html });
      const newPath = FileSystem.documentDirectory + "SmartFinance_Monthly_Report.pdf";

      await FileSystem.copyAsync({ from: uri, to: newPath });

      const available = await Sharing.isAvailableAsync();
      if (available) {
        await Sharing.shareAsync(newPath);
      } else {
        Alert.alert("Report Ready", "PDF saved successfully");
      }
    } catch (error) {
      console.error("Report Error:", error);
      Alert.alert("Error", "Failed to generate report. Please try again.");
    } finally {
      setGeneratingReport(false);
    }
  };

  const handleLogout = () => {
    Alert.alert("Sign Out", "Are you sure you want to logout?", [
      { text: "Cancel", style: "cancel" },
      { text: "Logout", style: "destructive", onPress: async () => await logout() },
    ]);
  };

  return (
    <ScrollView style={styles.container} showsVerticalScrollIndicator={false}>
      <View style={styles.header}>
        <Text style={styles.heading}>Profile</Text>
      </View>

      {/* Profile Hero */}
      <View style={styles.heroCard}>
        <TouchableOpacity onPress={pickImage} style={styles.avatarContainer}>
          {profileImage ? (
            <Image source={{ uri: profileImage }} style={styles.avatarImage} />
          ) : (
            <View style={styles.avatar}>
              <Text style={styles.avatarText}>
                {user?.name?.charAt(0)?.toUpperCase() || "U"}
              </Text>
            </View>
          )}
          <View style={styles.cameraBadge}>
            <Icon name="camera-outline" size={18} color="#fff" />
          </View>
        </TouchableOpacity>

        <Text style={styles.name}>{user?.name || "User"}</Text>
        <Text style={styles.email}>{user?.email || "user@example.com"}</Text>
        <Text style={styles.statusText}>Premium Member</Text>

        <View style={styles.badge}>
          <Icon name="shield-checkmark-outline" size={16} color="#fff" />
          <Text style={styles.badgeText}>FinSync Pro</Text>
        </View>
      </View>

      {/* Quick Actions */}
      <Text style={styles.sectionTitle}>Quick Actions</Text>
      <View style={styles.grid}>
        <TouchableOpacity style={styles.gridCard} onPress={() => navigation.navigate("Family")}>
          <Icon name="people-outline" size={32} color="#60A5FA" />
          <Text style={styles.gridText}>Family</Text>
        </TouchableOpacity>

        <TouchableOpacity style={styles.gridCard} onPress={() => navigation.navigate("Analytics")}>
          <Icon name="bar-chart-outline" size={32} color="#60A5FA" />
          <Text style={styles.gridText}>Analytics</Text>
        </TouchableOpacity>

        <TouchableOpacity style={styles.gridCard} onPress={generateReport} disabled={generatingReport}>
          {generatingReport ? (
            <ActivityIndicator color="#60A5FA" />
          ) : (
            <Icon name="document-text-outline" size={32} color="#60A5FA" />
          )}
          <Text style={styles.gridText}>Monthly Report</Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.gridCard}
          onPress={() => Alert.alert("AI Coach", "AI Finance Coach coming soon!")}
        >
          <Icon name="sparkles-outline" size={32} color="#60A5FA" />
          <Text style={styles.gridText}>AI Coach</Text>
        </TouchableOpacity>
      </View>

      {/* Achievement */}
      <View style={styles.achievementCard}>
        <Icon name="trophy-outline" size={32} color="#F59E0B" />
        <Text style={styles.achievementTitle}>Smart Saver</Text>
        <Text style={styles.achievementText}>
          You've tracked expenses consistently this month. Keep it up!
        </Text>
      </View>

      {/* Account Settings */}
      <Text style={styles.sectionTitle}>Account</Text>
      <View style={styles.menuCard}>
        {[
          { icon: "person-outline", title: "Edit Profile" },
          { icon: "lock-closed-outline", title: "Security" },
          { icon: "notifications-outline", title: "Notifications" },
          { icon: "phone-portrait-outline", title: "Connected Devices" },
        ].map((item, index) => (
          <TouchableOpacity key={index} style={styles.menuItem}>
            <Icon name={item.icon} size={22} color="#94A3B8" />
            <Text style={styles.menuText}>{item.title}</Text>
          </TouchableOpacity>
        ))}
      </View>

      {/* Support */}
      <Text style={styles.sectionTitle}>Support</Text>
      <View style={styles.menuCard}>
        {[
          { icon: "help-circle-outline", title: "Help Center" },
          { icon: "shield-checkmark-outline", title: "Privacy Policy" },
          { icon: "document-text-outline", title: "Terms & Conditions" },
          { icon: "information-circle-outline", title: "About Smart Finance" },
        ].map((item, index) => (
          <TouchableOpacity key={index} style={styles.menuItem}>
            <Icon name={item.icon} size={22} color="#94A3B8" />
            <Text style={styles.menuText}>{item.title}</Text>
          </TouchableOpacity>
        ))}
      </View>

      {/* Logout */}
      <TouchableOpacity style={styles.logoutButton} onPress={handleLogout}>
        <Icon name="log-out-outline" size={22} color="#fff" />
        <Text style={styles.logoutText}>Sign Out</Text>
      </TouchableOpacity>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0F172A",
  },
  header: {
    paddingHorizontal: 24,
    paddingTop: 60,
    paddingBottom: 20,
  },
  heading: {
    color: "#F1F5F9",
    fontSize: 32,
    fontWeight: "700",
  },

  heroCard: {
    backgroundColor: "#1E2937",
    marginHorizontal: 20,
    borderRadius: 28,
    padding: 32,
    alignItems: "center",
    marginBottom: 28,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.35,
    shadowRadius: 24,
    elevation: 12,
  },
  avatarContainer: {
    position: "relative",
    marginBottom: 16,
  },
  avatar: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: "#3B82F6",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 4,
    borderColor: "#60A5FA",
  },
  avatarImage: {
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 4,
    borderColor: "#60A5FA",
  },
  avatarText: {
    color: "#fff",
    fontSize: 42,
    fontWeight: "700",
  },
  cameraBadge: {
    position: "absolute",
    bottom: 4,
    right: 4,
    backgroundColor: "#3B82F6",
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: "#1E2937",
  },
  name: {
    color: "#F1F5F9",
    fontSize: 26,
    fontWeight: "700",
  },
  email: {
    color: "#94A3B8",
    fontSize: 16,
    marginTop: 4,
  },
  statusText: {
    color: "#BFDBFE",
    marginTop: 6,
    fontSize: 14,
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1E40AF",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
    marginTop: 16,
    gap: 8,
  },
  badgeText: {
    color: "#fff",
    fontWeight: "600",
  },

  sectionTitle: {
    color: "#F1F5F9",
    fontSize: 22,
    fontWeight: "700",
    marginHorizontal: 24,
    marginTop: 12,
    marginBottom: 16,
  },

  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 20,
    gap: 16,
    marginBottom: 24,
  },
  gridCard: {
    flex: 1,
    minWidth: "45%",
    backgroundColor: "#1E2937",
    borderRadius: 24,
    padding: 24,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  gridText: {
    color: "#F1F5F9",
    marginTop: 12,
    fontWeight: "600",
    fontSize: 15,
  },

  achievementCard: {
    backgroundColor: "#1E2937",
    marginHorizontal: 20,
    borderRadius: 24,
    padding: 24,
    marginBottom: 28,
    alignItems: "center",
  },
  achievementTitle: {
    color: "#F1F5F9",
    fontSize: 20,
    fontWeight: "700",
    marginTop: 12,
  },
  achievementText: {
    color: "#94A3B8",
    textAlign: "center",
    marginTop: 8,
    lineHeight: 22,
  },

  menuCard: {
    backgroundColor: "#1E2937",
    marginHorizontal: 20,
    borderRadius: 24,
    marginBottom: 24,
    overflow: "hidden",
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 20,
    gap: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#334155",
  },
  menuText: {
    color: "#E2E8F0",
    fontSize: 16,
    fontWeight: "500",
  },

  logoutButton: {
    flexDirection: "row",
    backgroundColor: "#EF4444",
    marginHorizontal: 20,
    padding: 18,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    marginBottom: 60,
  },
  logoutText: {
    color: "#fff",
    fontSize: 17,
    fontWeight: "600",
  },
});